# Generated by Django 2.2.1 on 2019-06-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('content', models.TextField(verbose_name='context')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='time_publish')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='time_update')),
            ],
        ),
        migrations.CreateModel(
            name='EvaPpa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_id', models.TextField(blank=True, db_column='LOT_ID', null=True)),
                ('glass_id', models.TextField(blank=True, db_column='GLASS_ID', null=True)),
                ('recipe', models.TextField(blank=True, db_column='RECIPE', null=True)),
                ('glass_start_time', models.DateTimeField(blank=True, db_column='GLASS_START_TIME', null=True)),
                ('glass_end_time', models.DateTimeField(blank=True, db_column='GLASS_END_TIME', null=True)),
                ('eva_chamber', models.TextField(blank=True, db_column='EVA_CHAMBER', null=True)),
                ('point_no', models.BigIntegerField(blank=True, db_column='POINT_NO', null=True)),
                ('pos_x', models.FloatField(blank=True, db_column='POS_X', null=True)),
                ('pos_y', models.FloatField(blank=True, db_column='POS_Y', null=True)),
                ('ppa_x', models.FloatField(blank=True, db_column='PPA_X', null=True)),
                ('ppa_y', models.FloatField(blank=True, db_column='PPA_Y', null=True)),
            ],
            options={
                'db_table': 'EVA_PPA',
            },
        ),
        migrations.CreateModel(
            name='MaskId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.TextField(blank=True, db_column='RECIPE', null=True)),
                ('glass_id', models.TextField(blank=True, db_column='GLASS_ID', null=True)),
                ('grp_label', models.BigIntegerField(blank=True, null=True)),
                ('eventtime', models.DateTimeField(blank=True, db_column='EVENTTIME', null=True)),
                ('mask_id', models.TextField(blank=True, db_column='MASK_ID', null=True)),
                ('x', models.TextField(blank=True, db_column='X', null=True)),
                ('y', models.TextField(blank=True, db_column='Y', null=True)),
                ('t', models.TextField(blank=True, db_column='T', null=True)),
                ('eva_chamber', models.TextField(blank=True, db_column='EVA_CHAMBER', null=True)),
                ('line', models.TextField(blank=True, null=True)),
                ('exp_label', models.BigIntegerField(blank=True, null=True)),
                ('prd_label', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'MASK_ID',
            },
        ),
        migrations.CreateModel(
            name='Mvi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.TextField(blank=True, db_column='RECIPE', null=True)),
                ('panel_id', models.TextField(blank=True, db_column='PANEL_ID', null=True)),
                ('glass_id', models.TextField(blank=True, db_column='GLASS_ID', null=True)),
                ('lastloggedintime', models.DateTimeField(blank=True, db_column='LASTLOGGEDINTIME', null=True)),
                ('lastloggedouttime', models.DateTimeField(blank=True, db_column='LASTLOGGEDOUTTIME', null=True)),
                ('dmem0', models.FloatField(blank=True, db_column='DMEM0', null=True)),
                ('dmem1', models.FloatField(blank=True, db_column='DMEM1', null=True)),
                ('dmem5', models.FloatField(blank=True, db_column='DMEM5', null=True)),
                ('loc_y', models.TextField(blank=True, db_column='LOC_Y', null=True)),
                ('loc_x', models.TextField(blank=True, db_column='LOC_X', null=True)),
                ('pos_x', models.FloatField(blank=True, db_column='POS_X', null=True)),
                ('pos_y', models.FloatField(blank=True, db_column='POS_Y', null=True)),
            ],
            options={
                'db_table': 'MVI',
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('age', models.IntegerField(blank=True, db_column='age', null=True)),
                ('company', models.CharField(blank=True, db_column='company', max_length=50, null=True)),
                ('description', models.TextField(blank=True, db_column='description', max_length=256, null=True)),
            ],
        ),
    ]
